### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by niekvanderkooy** [pagevamp/laravel-cloudwatch-logs#14]
Hi, could you release a new version to packagist, to include commit ed43b3a? Thanks!

**Comment by developernaren** [comment]
This broke when I tried 
https://github.com/pagevamp/laravel-cloudwatch-logs/pull/13
I remember that this is the PR that you sent. I did release a new version but it broke the install for me. So I reverted the release.

Someone said he was testing this for new laravel version. I will ask for update from him and let you know.

**Comment by wlarch** [comment]
I have been using the latest version with the following composer.json configuration : 

``` 
"require": {
        "php": "^7.3",
        "ext-curl": "*",
        "ext-json": "*",
        "laravel/framework": "^6.5",
        "laravel/helpers": "^1.1",
        "pagevamp/laravel-cloudwatch-logs": "dev-master",
}
```

The problem I have encountered is with using only cloudwatch as the application LOG_CHANNEL. I have left the "single" LOG_CHANNEL in my .env file and configured cloudwatch as follow in the logging.php configuration file : 

```
'cloudwatch' => [
            'name'        => env('CLOUDWATCH_LOG_NAME', ''),
            'region'      => env('CLOUDWATCH_LOG_REGION', ''),
            'credentials' => [
                'key'    => env('CLOUDWATCH_LOG_KEY', ''),
                'secret' => env('CLOUDWATCH_LOG_SECRET', '')
            ],
            'stream_name' => env('CLOUDWATCH_LOG_STREAM_NAME', 'laravel_app'),
            'retention'   => env('CLOUDWATCH_LOG_RETENTION_DAYS', 14),
            'group_name'  => env('CLOUDWATCH_LOG_GROUP_NAME', 'laravel_app'),
            'version'     => env('CLOUDWATCH_LOG_VERSION', 'latest'),
            'formatter'   => \Monolog\Formatter\JsonFormatter::class
        ],
```

I was able to receive Laravel logs into AWS Cloudwatch successfully :

![image](https://user-images.githubusercontent.com/5958500/71981705-ea3d0100-31f0-11ea-9cba-420183b7c856.png)

The option to use only cloudwatch log channel would be appreciated.

**Comment by niekvanderkooy** [comment]
> This broke when I tried
> #13
> I remember that this is the PR that you sent. I did release a new version but it broke the install for me. So I reverted the release.

Ah, I do apologize, I totally forgot you had done so in #13 ! I will close this issue so the discussion can stay there.

I'm still curious why it's not working for you - it has been working fine for me in production.

**Comment by developernaren** [comment]
@wlarch It is really no safe to use `dev-master` because every time something is added to master your composer will pull the master. I have release `0.1.1` by creating a tag from master. Please use this version. It seems like it is working. You and one other person has confirmed.

**Comment by wlarch** [comment]
Thanks for the information, it has been working fine since our release. I
will take a look at the 0.1.1 tag.

Best regards,

William L'Archevêque
+1 (438) 969-1770

**Comment by niekvanderkooy** [comment]
Note that Laravel 7 has been released in the meantime, so assuming the package also still works for that the composer.json should be changed to reflect this as well, or else the problem will occur all over again. Note that I havn't tested that this is indeed the case, but I would assume there aren't that many related breaking changes.

**Comment by developernaren** [comment]
Reopening this issue to address the new Larvavel 7 release. I will try and test. Would be awesome if you all can also help me test.

**Comment by developernaren** [comment]
Added support for Laravel 7. Please test and let me know if this works for you. I will release this if it works for everyone.
https://github.com/pagevamp/laravel-cloudwatch-logs/pull/17
I tested and is working fine for me in Laravel 7. Please use this in you composer.json

```json
"pagevamp/laravel-cloudwatch-logs": "dev-laravel-7-support"
```

**Comment by developernaren** [comment]
release 0.2.0 with laravel 7 support.
