### ISSUE TITLE
Laravel 6 support?

### ISSUE THREAD

**Issue by sil2** [pagevamp/laravel-cloudwatch-logs#15]
Could you addd laravel 6 support pls?
Just exclude illuminate/support from requires  - this should fix the issue

**Comment by developernaren** [comment]
@sil2 just send a PR. I will review and merge.

**Comment by developernaren** [comment]
@sil2  Can you please try `0.1.1`. I have just released with support for laravel 6.

**Comment by codeduction** [comment]
The released 0.1.1 is working for me.

**Comment by developernaren** [comment]
@codeduction thanks for confirming. Looks like it's working. I will close this issue.
