### ISSUE TITLE
Monolog 2.0 compatibility

### ISSUE THREAD

**Issue by particleflux** [pagevamp/laravel-cloudwatch-logs#18]
With the release of [v2.0.0](https://github.com/maxbanton/cwh/releases/tag/v2.0.0) of `maxbanton/cwh` , that lib is now Monolog 2.0 compatible.

Would be awesome if that could be supported here as well :)

**Comment by developernaren** [comment]
https://github.com/pagevamp/laravel-cloudwatch-logs/pull/17 I created this PR for Larvael 7. it includes monolog 2 upgrade. Can you try this out?

**Comment by particleflux** [comment]
Seems to work, despite the fact that you seem to have missed a place to update the disabled flag.
I added a comment to the PR.

Tested with laravel 5.8 and monolog 2

**Comment by developernaren** [comment]
Release 0.2.0 with these changes.

**Comment by particleflux** [comment]
Thanks for the fix :+1:
