### ISSUE TITLE
Unable to create configured logger. Using emergency logger.

### ISSUE THREAD

**Issue by noil** [pagevamp/laravel-cloudwatch-logs#19]
I followed to readme.md and got error
```json
 {
    "message": "Unable to create configured logger. Using emergency logger.",
    "context": {
        "exception": {
            "class": "ErrorException",
            "message": "Undefined index: driver",
            "code": 0,
            "file": "/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:184"
        }
    },
    "level": 600,
    "level_name": "EMERGENCY",
    "channel": "channel_1",
    "datetime": {
        "date": "2020-04-13 14:46:01.110488",
        "timezone_type": 3,
        "timezone": "UTC"
    },
    "extra": []
}
```
Version laravel 5.6 updated from laraval 5.5

**Comment by noil** [comment]
I tried to replace the default logging

**Comment by superern** [comment]
I was confused when you said replace with the default logging (stack). Then found @developernaren 's answer and now I understand.

https://github.com/pagevamp/laravel-cloudwatch-logs/issues/7#issuecomment-463907907

Works after reverting back from 
LOG_CHANNEL=cloudwatch
to
LOG_CHANNEL=stack
(or daily or single, etc)
