### ISSUE TITLE
Updating to Laravel 7 Causes InvalidSequenceTokenException

### ISSUE THREAD

**Issue by twickstrom** [pagevamp/laravel-cloudwatch-logs#22]
Error executing "PutLogEvents" on "https://logs.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://logs.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:

```
{
  "__type": "InvalidSequenceTokenException",
  "expectedSequenceToken": "49597042187774269928909159510882100678280996470456157 (truncated...)"
}
```
   
InvalidSequenceTokenException (client): The given sequenceToken is invalid. The next expected sequenceToken is:
49597042187774269928909159510882100678280996470456157586

**Comment by developernaren** [comment]
Please let know the exact version of Laravel 7. May be something changed in one of the new releases to break this. When I tested it worked. I will try and replicate this error.
