### ISSUE TITLE
Laravel 8. Undefined index: via

### ISSUE THREAD

**Issue by michael-paktolus** [pagevamp/laravel-cloudwatch-logs#31]
I have next error in my laravel.log:
`laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (ErrorException(code: 0): Undefined index: via at \\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:227)
`
It is require 'via' key: https://laravel.com/docs/8.x/logging#creating-custom-channels-via-factories

**Comment by developernaren** [comment]
The way this is implemented right now is that it listens to log event and logs to aws. This package does not work as a standalone logging package. I have actually implemented this to work as a driver in this PR. https://github.com/pagevamp/laravel-cloudwatch-logs/pull/24
Would you be willing to test this and give me feedback if this works?

**Comment by michael-paktolus** [comment]
Hello developernaren.

Yes, it is working good. Are you planning merge it to the master? I want to install it with composer.

**Comment by developernaren** [comment]
@michael-paktolus thank you for testing.
I made some changes and added a readme too. Can you please test this once more? If everything works, I will release this as `v1.0`

**Comment by michael-paktolus** [comment]
Hello, @developernaren, thank you for your work. The package working good.
As I see you removed 'disabled' key, but it is still present config/logging.php

**Comment by developernaren** [comment]
@michael-paktolus nice catch, removed that, will create a release now.

**Comment by developernaren** [comment]
released: https://github.com/pagevamp/laravel-cloudwatch-logs/releases/tag/v1.0.1
will close this issue.
