### ISSUE TITLE
Laravel 10 support?

### ISSUE THREAD

**Issue by bassem-shoukry** [pagevamp/laravel-cloudwatch-logs#40]

**Comment by drewg2009** [comment]
I'm trying to upgrade to laravel 10 and I unable to due the following error:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v10.0.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.1 (conflict analysis result)
    - illuminate/support[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.2.4) does not satisfy that requirement.
    - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.2.4) does not satisfy that requirement.
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.2.4) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.2.4) does not satisfy that requirement.
    - pagevamp/laravel-cloudwatch-logs v1.0.2 requires illuminate/support ^5.1 || ^6.0 || ^7.0 || ^8.0 || ^9.0 -> satisfiable by illuminate/support[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev].
    - pagevamp/laravel-cloudwatch-logs v1.0.1 requires illuminate/support ^5.1 || ^6.0 || ^7.0 || ^8.0 -> satisfiable by illuminate/support[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev], laravel/framework[v10.0.0, ..., 10.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0, ..., 10.x-dev].
    - Root composer.json requires pagevamp/laravel-cloudwatch-logs ^1.0 -> satisfiable by pagevamp/laravel-cloudwatch-logs[v1.0.1, v1.0.2].`

Are we able to prioritize this?

**Comment by stefanrakicfaxi** [comment]
I have the same problem this package blocks my transition to Laravel 10

**Comment by stefanrakicfaxi** [comment]
@developernaren It's works

**Comment by developernaren** [comment]
closing this ticket, a new version has been released to support laravel 10
