### ISSUE TITLE
stack traces

### ISSUE THREAD

**Issue by richpeers** [pagevamp/laravel-cloudwatch-logs#6]
Hey, great package.
As ive set this up ive notinced a couple of commits around the formatter, LinFormater and JsonFormatter.
Is there some way to include the stack traces. theres mention in Monolog/Formatters/JsonFormatter but not been able to set this via the logging config, any ideas?
Keep up the great work!

**Comment by developernaren** [comment]
Just added the config in version 0.0.5

https://github.com/pagevamp/laravel-cloudwatch-logs/blob/master/config/logging.php
Take a look at this file, you should be able to set the callable like in this file.

**Comment by developernaren** [comment]
You can set the `formatter` in config now, just pushed the version `0.0.5`. Please refer to this file https://github.com/pagevamp/laravel-cloudwatch-logs/blob/master/config/logging.php.

**Comment by richpeers** [comment]
Thanks @developernaren 
i just extended Monolog\Formatter\JsonFormatter and passed that class to logging.channels.cloudwatch.formatter in config
